split testing into distinct steps

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -20,21 +20,34 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: "3.10"
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           python -m pip install .[tests]
-      - name: Test with pytest
-        # Below, we first run pytest in the `tests/` folder. Because we use a `src`
-        # layout, this will fail if the package is not installed correctly.
-        # Afterwards, we execute all doctests in the `src` tree. This will NOT run with
-        # the installed code, but it doesn't matter, because we already know it is
-        # installable from the first line.
-        run: |
-          COVERAGE_FILE=".coverage.tests" pytest --cov=lydata --cov-config=pyproject.toml tests
-          COVERAGE_FILE=".coverage.docs" pytest --cov=lydata --cov-config=pyproject.toml --doctest-modules src
+
+      # Below, we first run pytest in the `tests/` folder. Because we use a `src`
+      # layout, this will fail if the package is not installed correctly.
+      - name: Test package is installable
+        run: pytest --cov=lydata --cov-config=pyproject.toml tests
+        with:
+          COVERAGE_FILE: .coverage.is_installable
+
+      # Now, we execute all doctests in the `src` tree. This will NOT run with
+      # the installed code, but it doesn't matter, because we already know it is
+      # installable from the step above.
+      - name: Run doctests
+        if: success() || failure()   # run these even if previous step fails
+        run: pytest --cov=lydata --cov-config=pyproject.toml --doctest-modules src
+        with:
+          COVERAGE_FILE: .coverage.doctests
+
+      # Lastly, we collect all files that start with `.coverage` into one file and
+      # create a report either as a comment on the PR or in a separate branch if its
+      # a commit to the main branch. From that branch we can put badges and coverage
+      # reports into e.g. our main README.md 
       - name: Add coverage comment
-        if: success() || failure()
+        if: success() || failure()   # run these even if previous step fails
         uses: py-cov-action/python-coverage-comment-action@v3
         with:
           GITHUB_TOKEN: ${{ github.token }}
